### ISSUE TITLE
Database corrupted

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/clarence#2]
```
/app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `initialize': database disk image is malformed (SQLite3::CorruptException)
 	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `new'
 	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `prepare'
 	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:134:in `execute'
 	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite_magic-0.0.3/lib/sqlite_magic.rb:93:in `block in save_data'
 	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite_magic-0.0.3/lib/sqlite_magic.rb:88:in `each'
 	from /app/vendor/bundle/ruby/1.9.1/gems/sqlite_magic-0.0.3/lib/sqlite_magic.rb:88:in `save_data'
 	from /app/vendor/bundle/ruby/1.9.1/bundler/gems/scraperwiki-ruby-fc5017681250/lib/scraperwiki.rb:89:in `save_sqlite'
 	from scraper.rb:82:in `block (2 levels) in <main>'
 	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `block in each'
 	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `upto'
 	from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
 	from scraper.rb:66:in `block in <main>'
 	from /app/vendor/bundle/ruby/1.9.1/gems/mechanize-2.5.1/lib/mechanize.rb:409:in `get'
 	from scraper.rb:65:in `<main>'
```

**Comment by henare** [comment]
Because this was a problem with morph I recovered the database by doing the following on the server:

```
root@li421-88:~# cd /var/www/shared/db/scrapers/data/planningalerts-scrapers/clarence/
root@li421-88:/var/www/shared/db/scrapers/data/planningalerts-scrapers/clarence# sqlite3 data.sqlite ".dump" | sqlite3 new.db
root@li421-88:/var/www/shared/db/scrapers/data/planningalerts-scrapers/clarence# mv new.db data.sqlite
```

**Comment by henare** [comment]
We thought it brought the history back but it didn't.

**Comment by henare** [comment]
I restored a backup from 15 days ago (that's when the last data was written to the database according to the morph page for this scraper) with the following command:

`duply sqlite fetch planningalerts-scrapers/clarence/data.sqlite /root/data.sqlite 15D`

I checked the restored file before copying it over the live version. We now have 1922 records so I think this is properly fixed now.
